# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'
#
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
- task: CMake@1
  inputs:
    workingDirectory: 'CMake'
    cmakeArgs: '-S ../ -B ./bin -G "Visual Studio 16 2019"'
- task: CMake@1
  inputs:
    workingDirectory: 'CMake'
    cmakeArgs: '--build ./bin'
#- task: CmdLine@2
#  inputs:
#    workingDirectory: 'CMake/bin/src/Debug'
#    script: 'Project.exe'
- task: PublishSymbols@2
  inputs:
    SearchPattern: '**/bin/**/*.pdb'
    SymbolServerType: 'TeamServices'
- task: CopyFiles@2
  inputs:
    #sourceFolder: '$(Build.SourcesDirectory)'
    sourceFolder: 'CMake/bin/src/Debug'
    contents: '?(*.exe|*.dll|*.pdb)'
    #contents: '**/$(BuildConfiguration)/**/?(*.exe|*.dll|*.pdb)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: CmdLine@2
  inputs:
    workingDirectory: 'External'
    script: 'SourceIndexer.exe $(Build.ArtifactStagingDirectory)/Project.pdb ../'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop